export const jobs = [
	"Chief Happiness Officer",
	"Data Analyst",
	"Content Creator",
	"Urban Planner",
	"Social Media Manager",
	"Environmental Scientist",
	"Cybersecurity Specialist",
	"Graphic Designer",
	"Nurse Practitioner",
	"Software Engineer",
	"Financial Analyst",
	"Marketing Coordinator",
	"Human Resources Manager",
	"Digital Nomad Consultant",
	"Wilderness Guide",
	"Culinary Artist",
	"Fitness Trainer",
	"Fashion Stylist",
	"Video Game Developer",
	"Patent Attorney",
	"Child Psychologist",
	"Solar Energy Technician",
	"Blockchain Developer",
	"Wildlife Biologist",
	"User Experience Designer",
	"Wedding Planner",
	"Music Therapist",
	"Disaster Relief Coordinator",
	"Ethical Hacker",
	"Sustainability Consultant",
	"Speech-Language Pathologist",
	"Robotics Engineer",
	"Art Therapist",
	"Investment Banker",
	"Yoga Instructor",
	"Brand Ambassador",
	"Biomedical Engineer",
	"Conflict Resolution Mediator",
	"Virtual Reality Designer",
	"Interior Decorator",
	"Creative Director",
	"Animal Behaviorist",
	"SEO Specialist",
	"Forensic Scientist",
	"Aerospace Engineer",
	"Urban Gardener",
	"Technical Writer",
	"Immigration Lawyer",
	"Ethnobotanist",
	"Public Relations Specialist",
	"Brewmaster",
	"Disaster Recovery Specialist",
	"Patent Examiner",
	"Environmental Engineer",
	"App Developer",
	"Wedding Photographer",
	"Wilderness Survival Instructor",
	"Genetic Counselor",
	"Quantum Physicist",
	"Humanitarian Aid Worker",
	"Talent Acquisition Specialist",
	"Automotive Designer",
	"Nutritionist",
	"Forestry Technician",
	"UX Researcher",
	"Climate Change Analyst",
	"Virtual Assistant",
	"Occupational Therapist",
	"Marine Biologist",
	"Futurist",
	"SEO Copywriter",
	"Cruise Ship Entertainer",
	"Industrial Designer",
	"Sustainable Architect",
	"Immigration Consultant",
	"Disaster Relief Volunteer Coordinator",
	"Data Scientist",
	"Animal Trainer",
	"Urban Farmer",
	"Behavioral Economist",
	"Patent Agent",
	"Art Director",
	"Water Quality Technician",
	"Renewable Energy Engineer",
	"Content Strategist",
	"Wildlife Conservationist",
	"Blockchain Consultant",
	"Health Coach",
	"Environmental Educator",
	"Solar Panel Installer",
	"Social Worker",
	"Mobile App Tester",
	"Cryptocurrency Analyst",
	"Personal Finance Advisor",
	"Sustainable Fashion Designer",
	"UX/UI Designer",
	"Wilderness First Responder",
	"Industrial Hygienist",
	"Community Organizer",
	"Virtual Event Planner",
]
